In [1]:
import pandas as pd
pd.options.display.max_rows = 999
pd.options.display.max_columns = 999
import numpy as np
import cv2
import matplotlib.pyplot as plt
import seaborn as sns
import os
import joblib
import pickle
from utils import flat, trace
from tqdm import tqdm
import psutil
import torch
import gc
from itertools import product
from multiprocessing import Pool
from tqdm import tqdm
from data import RFCXDataset
from model import kaggle_metric
from utils import sigmoid

In [2]:
data_dir = '../../input/kaggle/train'
fnames = os.listdir(data_dir)
recording_ids = [x[:-5] for x in fnames]
print(len(fnames))
train_tp = pd.read_csv('../../input/kaggle/train_tp.csv', index_col='recording_id')
train_fp = pd.read_csv('../../input/kaggle/train_fp.csv', index_col='recording_id')
sample_submission = pd.read_csv('../../input/kaggle/sample_submission.csv')
folds = joblib.load('folds.jl')
print(train_tp.shape)
display(train_tp.head())
print(train_fp.shape)
display(train_fp.head())

4729
(1216, 6)


species_id  songtype_id    t_min     f_min    t_max     f_max
recording_id                                                               
003bec244             14            1  44.5440  2531.250  45.1307   5531.25
006ab765f             23            1  39.9615  7235.160  46.0452  11283.40
007f87ba2             12            1  39.1360   562.500  42.2720   3281.25
0099c367b             17            4  51.4206  1464.260  55.1996   4565.04
009b760e6             10            1  50.0854   947.461  52.5293  10852.70

(7781, 6)


species_id  songtype_id    t_min       f_min    t_max  \
recording_id                                                          
00204008d             21            1  13.8400   3281.2500  14.9333   
00204008d              8            1  24.4960   3750.0000  28.6187   
00204008d              4            1  15.0027   2343.7500  16.8587   
003b04435             22            1  43.2533  10687.5000  44.8587   
003b04435             23            1   9.1254   7235.1562  15.2091   

                   f_max  
recording_id              
00204008d      4125.0000  
00204008d      5531.2500  
00204008d      4218.7500  
003b04435     13687.5000  
003b04435     11283.3984

In [7]:
sub = pd.read_csv('submission.csv', index_col='recording_id')
display(sub)
display(sub.describe())

s0        s1        s2        s3        s4        s5  \
recording_id                                                               
73c482b64     0.993520  0.030332  0.050700  0.941412  0.211176  0.403374   
afaa8d38f     0.912487  0.303974  0.080591  0.733273  0.967078  0.279590   
074cf066a     0.382550  0.282504  0.825998  0.096949  0.418305  0.157411   
2a7255b0c     0.990820  0.923954  0.080412  0.562972  0.613984  0.241469   
28ed37c9a     0.262467  0.331431  0.427942  0.867403  0.261143  0.929644   
8bf90ebb9     0.207905  0.974910  0.194285  0.962516  0.134518  0.281184   
a82802bd2     0.270048  0.617183  0.208113  0.977052  0.231861  0.214787   
ed8b65c55     0.190514  0.290031  0.587511  0.707793  0.295910  0.441680   
edf9fe22d     0.970775  0.116677  0.062330  0.860816  0.133922  0.500269   
d1477bf79     0.988491  0.028261  0.098397  0.902400  0.202326  0.171495   
be96c9133     0.376110  0.597548  0.114334  0.924518  0.631037  0.262747   
fd7cc65e1     0.268661  0.178943  0.570817  0.776132  0.496081  0.530741   
1441fe517     0.567145  0.992464  0.687411  0.864461  0.104882  0.373373   
d82a81c98     0.312367  0.258187  0.990850  0.840412  0.353617  0.366655   
dd81b8980     0.943412  0.712974  0.071953  0.927832  0.154787  0.145817   
579bcf9e0     0.354888  0.252836  0.552664  0.366655  0.343004  0.588901   
2e1ee378c     0.321792  0.985972  0.213314  0.965666  0.594731  0.578874   
e4d8a25be     0.415884  0.397559  0.442529  0.950517  0.139866  0.177751   
2d775f3bf     0.488966  0.978320  0.135322  0.501629  0.222059  0.360519   
8f0daaed9     0.448170  0.236436  0.189587  0.971443  0.731936  0.418960   
0c1bcc7ba     0.284442  0.390668  0.426506  0.928535  0.105929  0.332718   
0268057eb     0.319302  0.129728  0.079053  0.802736  0.257469  0.372401   
819afd877     0.242157  0.268035  0.738756  0.140954  0.667195  0.959290   
bfd6218e4     0.337462  0.122673  0.383819  0.850717  0.417971  0.422783   
63e47e918     0.423633  0.750406  0.688151  0.857802  0.331586  0.370817   
a7d5f1883     0.380296  0.750417  0.420795  0.468177  0.275839  0.137262   
8253e1640     0.248934  0.215813  0.656265  0.096483  0.686666  0.776890   
687733bf1     0.256519  0.900245  0.176595  0.970629  0.273577  0.898476   
0b5a33bb8     0.497638  0.230869  0.497870  0.816588  0.295287  0.653860   
dfe828cba     0.430326  0.873618  0.372327  0.920093  0.329785  0.326661   
749447350     0.274405  0.234991  0.725710  0.174851  0.373809  0.227747   
ccee900dd     0.283487  0.435751  0.419113  0.924146  0.203064  0.483526   
426700103     0.325905  0.436226  0.574170  0.225689  0.466171  0.346616   
71a271bcf     0.406899  0.051255  0.064440  0.766930  0.983057  0.333053   
a66d44311     0.473127  0.940482  0.312846  0.939504  0.303589  0.717181   
6b100fbfb     0.474548  0.147102  0.255767  0.794823  0.408783  0.690930   
aa524a44b     0.537855  0.187390  0.303485  0.365478  0.172235  0.733900   
71f0fd83e     0.306667  0.177983  0.540181  0.702164  0.744799  0.487368   
ff6ba53d5     0.367280  0.729961  0.135637  0.969633  0.571953  0.114750   
955cbc31c     0.377720  0.059758  0.102529  0.846941  0.993039  0.384738   
16cf75798     0.587426  0.962127  0.191413  0.852039  0.531660  0.195625   
b2884fc1f     0.585501  0.809292  0.103071  0.960879  0.372897  0.551661   
da329b0a5     0.273632  0.127670  0.074028  0.847974  0.982135  0.436722   
3508bf762     0.993762  0.982742  0.220134  0.892698  0.159052  0.171032   
a277651b1     0.428366  0.437234  0.634903  0.477592  0.414473  0.211646   
c5290bfd1     0.395965  0.245899  0.094604  0.954582  0.985798  0.390634   
950d678b8     0.281731  0.291771  0.642958  0.716885  0.272924  0.147002   
dacda707f     0.162461  0.593106  0.187653  0.970732  0.142947  0.139244   
de7922c14     0.257314  0.396364  0.141012  0.959810  0.341487  0.383323   
581d07559     0.237074  0.126157  0.267976  0.953103  0.451426  0.374933   
d4e5616b6     0.319359  0.189242  0.549070  0.931828  0.283471  0.16

s0          s1          s2          s3          s4          s5  \
count  945.000000  945.000000  945.000000  945.000000  945.000000  945.000000   
mean     0.399510    0.412535    0.413781    0.775564    0.368171    0.427416   
std      0.220499    0.309965    0.272892    0.262115    0.209531    0.214412   
min      0.058366    0.027967    0.047624    0.059092    0.058343    0.074861   
25%      0.255980    0.169184    0.166240    0.712257    0.204905    0.259519   
50%      0.342214    0.290031    0.358319    0.903192    0.326205    0.385465   
75%      0.451691    0.667685    0.629559    0.952873    0.478614    0.567205   
max      0.993762    0.993202    0.995770    0.985371    0.994814    0.987151   

               s6          s7          s8          s9         s10         s11  \
count  945.000000  945.000000  945.000000  945.000000  945.000000  945.000000   
mean     0.360654    0.513059    0.508412    0.444921    0.442136    0.374009   
std      0.177136    0.286647    0.237535    0.235962    0.197482    0.264591   
min      0.077205    0.069819    0.040817    0.066293    0.061473    0.073426   
25%      0.226757    0.263318    0.336412    0.233231    0.304019    0.177695   
50%      0.334500    0.398448    0.520534    0.422630    0.422127    0.274763   
75%      0.470350    0.802006    0.684561    0.632402    0.558360    0.477543   
max      0.989330    0.988314    0.995963    0.993637    0.992002    0.995416   

              s12         s13         s14         s15         s16         s17  \
count  945.000000  945.000000  945.000000  945.000000  945.000000  945.000000   
mean     0.495155    0.566205    0.354265    0.480839    0.403470    0.213732   
std      0.294546    0.230794    0.249950    0.287668    0.198584    0.180449   
min      0.055047    0.047045    0.072994    0.032980    0.101726    0.031047   
25%      0.225370    0.424864    0.174357    0.207602    0.241809    0.090215   
50%      0.443334    0.631709    0.271426    0.479472    0.366630    0.154541   
75%      0.758446    0.742203    0.437957    0.730889    0.515123    0.276974   
max      0.990138    0.993667    0.994372    0.991921    0.995366    0.987852   

              s18         s19         s20         s21         s22         s23  
count  945.000000  945.000000  945.000000  945.000000  945.000000  945.000000  
mean     0.605932    0.378871    0.449714    0.478162    0.425217    0.424009  
std      0.265974    0.228421    0.258789    0.198967    0.235755    0.260919  
min      0.129321    0.059358    0.061618    0.159548    0.006015    0.033348  
25%      0.377019    0.204995    0.210845    0.319064    0.236944    0.176005  
50%      0.537914    0.315919    0.406538    0.439822    0.440134    0.419135  
75%      0.914151    0.531087    0.694704    0.600606    0.593415    0.626573  
max      0.989854    0.989765    0.995649    0.997606    0.997579    0.994196

In [4]:
sub.mean()

s0     0.413186
s1     0.400552
s2     0.423287
s3     0.811315
s4     0.391724
s5     0.464032
s6     0.389625
s7     0.492545
s8     0.457904
s9     0.491253
s10    0.472529
s11    0.385916
s12    0.537072
s13    0.515552
s14    0.364734
s15    0.481834
s16    0.301062
s17    0.222266
s18    0.752366
s19    0.367232
s20    0.516423
s21    0.414319
s22    0.518471
s23    0.418675
dtype: float64

In [5]:
sub.mean().mean()

0.05815756635761571

In [42]:
input = torch.tensor([[1,2,-1,-2]]).float()
target = torch.tensor([[1.,0.5,0,0]]).float()
input_differences = input.unsqueeze(1) - input.unsqueeze(2)
target_differences = target.unsqueeze(2) - target.unsqueeze(1)
exps = input_differences.exp() * torch.maximum(torch.tensor(0), target_differences)
lsep = torch.log(1 + exps.sum(2).sum(1))

In [50]:
xtorch.where(target_differences<0, torch.tensor(0.), target_differences)

tensor([[[0.0000, 0.5000, 1.0000, 1.0000],
         [0.0000, 0.0000, 0.5000, 0.5000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]]])

In [43]:
input_differences

tensor([[[ 0.,  1., -2., -3.],
         [-1.,  0., -3., -4.],
         [ 2.,  3.,  0., -1.],
         [ 3.,  4.,  1.,  0.]]])

In [44]:
target_differences

tensor([[[ 0.0000,  0.5000,  1.0000,  1.0000],
         [-0.5000,  0.0000,  0.5000,  0.5000],
         [-1.0000, -0.5000,  0.0000,  0.0000],
         [-1.0000, -0.5000,  0.0000,  0.0000]]])

In [45]:
exps

tensor([[[0.0000, 1.3591, 0.1353, 0.0498],
         [0.0000, 0.0000, 0.0249, 0.0092],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]]])

In [46]:
lsep

tensor([0.9471])